name: Compile, Test, & Deploy
on: [push, pull_request]

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: split the yaml
      run: |
        mkdir _build _build/en _build/fr _build/theme
        python splityaml.py openapi.yaml en _build/en/openapi-en.json
        python splityaml.py openapi.yaml fr _build/fr/openapi-fr.json

    - name: Test that our specs are valid
      run: |
        cp -r schemas _build
        openapi-spec-validator _build/en/openapi-en.json
        openapi-spec-validator _build/fr/openapi-fr.json
        cp index.html _build && cp index-en.html _build/en && cp index-fr.html _build/fr

    - name: Download and unpack the theme
      run: |
        curl -L "https://github.com/wet-boew/themes-cdn/archive/v11.0.0-gcweb.tar.gz" | tar -zvx --strip-components 1 --directory=_build/theme

    - name: GitHub Pages action
      # only deploys to gh-pages if ref is main branch
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build
