name: Compile, Test, & Deploy
on: [push, pull_request]

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: split the yaml
      run: |
        mkdir _build
        python splityaml.py openapi.yaml en _build/openapi-en.json
        python splityaml.py openapi.yaml fr _build/openapi-fr.json

    - name: Test that our specs are valid
      run: |
        cp -r schemas _build
        openapi-spec-validator _build/openapi-en.json
        openapi-spec-validator _build/openapi-fr.json
        cp index.html index-en.html index-fr.html _build

    - name: GitHub Pages action
      # only deploys to gh-pages if ref is main branch
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build
