name: deploy-docs

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: split the yaml
      run: |
        mkdir _build
        python3 splityaml.py openapi.yaml en _build/openapi-en.json
        python3 splityaml.py openapi.yaml fr _build/openapi-fr.json
        cp index.html index-en.html index-fr.html _build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build
